### GET ALL TODOS
GET http://localhost:3000/api/v1/todos

### GET TODO BY ID
GET http://localhost:3000/api/v1/todos/8b2fc14e

### CREATE TODO
POST http://localhost:3000/api/v1/todos
content-type: application/json

{
  "title": "Go to the laundry"
}

### UPDATE TODO BY ID
PATCH http://localhost:3000/api/v1/todos/b981e38f

### DELETE TODO BY ID
DELETE http://localhost:3000/api/v1/todos/b981e38f
